import Head from "next/head";
import { Button } from "@mui/material";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useAuth } from "../../context/auth";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useAuth();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button variant="contained" onClick={() => router.push("/messages")}>
          Go to messages
        </Button>
      </main>
    </>
  );
}
